import {create,globals} from 'webgpu';
import fs from 'node:fs';import vm from 'node:vm';
Object.assign(globalThis,globals);
const nativeBackend=process.env.SHORE_NATIVE_BACKEND||'null';const gpu=create(['backend='+nativeBackend]);let device,frame;const shaderAudit=[];
const navigatorGPU={getPreferredCanvasFormat(){return 'bgra8unorm'},requestAdapter:async options=>{const adapter=await gpu.requestAdapter(options);if(adapter){const request=adapter.requestDevice.bind(adapter);adapter.requestDevice=async options=>{device=await request(options);const makeShader=device.createShaderModule.bind(device);device.createShaderModule=d=>{const m=makeShader(d);m.getCompilationInfo().then(info=>{for(const error of info.messages)if(error.type==="error")console.error("WGSL ERROR",d.label,error.message,error.lineNum);});return m;};const makePipeline=device.createRenderPipeline.bind(device);device.createRenderPipeline=descriptor=>{device.pushErrorScope("validation");const pipeline=makePipeline(descriptor);device.popErrorScope().then(error=>{if(error)console.error("SYNC PIPELINE ERROR",descriptor.label,error.message,JSON.stringify(descriptor.fragment?.targets));});return pipeline;};for(const method of ["createRenderPipelineAsync","createComputePipelineAsync"]){const original=device[method].bind(device);device[method]=async descriptor=>{try{return await original(descriptor)}catch(error){console.error("PIPELINE FAILURE",descriptor.label,error);throw error}};}device.addEventListener("uncapturederror",e=>console.error("native validation",e.error?.message));if(process.env.SHORE_SHADER_AUDIT){const createShader=device.createShaderModule.bind(device);device.createShaderModule=descriptor=>{if(descriptor.code.includes("0.02037"))shaderAudit.push({label:descriptor.label,samples:(descriptor.code.match(/textureSample(?:Level|Bias|Grad|Compare)?\(/g)||[]).length,loads:(descriptor.code.match(/textureLoad\(/g)||[]).length,bytes:descriptor.code.length});return createShader(descriptor)};}return device;};}return adapter;}};
Object.defineProperty(globalThis,'navigator',{value:{gpu:process.env.SHORE_FORCE_FALLBACK?null:navigatorGPU,userAgent:process.env.SHORE_MOBILE?'iPhone native software QA':'Native production-bundle validation'},configurable:true});
globalThis.window=globalThis;globalThis.self={requestAnimationFrame(callback){frame=callback;return 1},cancelAnimationFrame(){}};globalThis.requestAnimationFrame=callback=>setImmediate(()=>callback(performance.now()));globalThis.addEventListener=()=>{};globalThis.innerWidth=640;globalThis.innerHeight=426;globalThis.devicePixelRatio=1;
const elements=new Map();const element=id=>{if(!elements.has(id))elements.set(id,{id,style:{},hidden:false,dataset:{},tagName:'DIV',addEventListener(){},removeEventListener(){},setAttribute(){},focus(){},setPointerCapture(){},hasPointerCapture(){return false},appendChild(){},getBoundingClientRect(){return {width:96,height:96,left:0,top:0}}});return elements.get(id)};
const canvas=element('view');canvas.width=960;canvas.height=640;let target,configuration;
const context={configure(c){configuration=c;target?.destroy();target=null},getCurrentTexture(){if(!target||target.width!==canvas.width||target.height!==canvas.height){target?.destroy();target=device.createTexture({size:[canvas.width,canvas.height],format:configuration.format,usage:GPUTextureUsage.RENDER_ATTACHMENT|GPUTextureUsage.COPY_SRC});}return target},unconfigure(){}};canvas.getContext=()=>context;
globalThis.document={hidden:false,getElementById:element,querySelectorAll(){return ['wide','shore','water','grass'].map(name=>{const e=element(name);e.dataset.view=name;return e})},addEventListener(){},createElementNS(){return element('temporary-canvas')}};
globalThis.shoreNativeTextureDecoder=async bytes=>{const {PNG}=await import('pngjs');const p=PNG.sync.read(Buffer.from(bytes));return {data:new Uint8Array(p.data),width:p.width,height:p.height};};
const html=fs.readFileSync(process.env.SHORE_HTML||'dist/index.html','utf8'),script=html.match(/<script>([\s\S]*)<\/script>/)[1];vm.runInThisContext(script,{filename:'production-bundle.js'});
for(let i=0;i<500&&!window.shoreBackend;i++)await new Promise(resolve=>setTimeout(resolve,10));
const app=window.shoreDemoGPU,events=[];const captureDir=process.env.SHORE_CAPTURE_DIR||'qa/interaction-captures';fs.mkdirSync(captureDir,{recursive:true});
async function capture(name,full=false){if(process.env.SHORE_SKIP_CAPTURES)return;if(full){app.renderer.setSize(960,640,false);app.shore.camera.aspect=1.5;app.shore.camera.updateProjectionMatrix();}frame?.(performance.now());await device.queue.onSubmittedWorkDone();await new Promise(resolve=>setImmediate(resolve));if(nativeBackend==='null')return;const width=canvas.width,height=canvas.height,row=Math.ceil(width*4/256)*256,buffer=device.createBuffer({size:row*height,usage:GPUBufferUsage.COPY_DST|GPUBufferUsage.MAP_READ}),encoder=device.createCommandEncoder();encoder.copyTextureToBuffer({texture:target},{buffer,bytesPerRow:row},[width,height]);device.queue.submit([encoder.finish()]);await buffer.mapAsync(GPUMapMode.READ);const mapped=new Uint8Array(buffer.getMappedRange()),pixels=new Uint8Array(width*height*4);for(let y=0;y<height;y++)pixels.set(mapped.subarray(y*row,y*row+width*4),y*width*4);buffer.unmap();buffer.destroy();if(configuration.format.startsWith('bgra'))for(let i=0;i<pixels.length;i+=4){const r=pixels[i];pixels[i]=pixels[i+2];pixels[i+2]=r;}const {PNG}=await import('pngjs');const png=new PNG({width,height});png.data=Buffer.from(pixels);fs.writeFileSync(captureDir+'/'+name+'.png',PNG.sync.write(png));if(full){app.renderer.setSize(innerWidth,innerHeight,false);app.shore.camera.aspect=innerWidth/innerHeight;app.shore.camera.updateProjectionMatrix();}}


if(!app)throw Error('Boot failed');app.pause(true);const realFence=device.queue.onSubmittedWorkDone.bind(device.queue),held=[];device.queue.onSubmittedWorkDone=()=>new Promise(resolve=>held.push(resolve));
frame(performance.now());frame(performance.now());frame(performance.now());const busy=app.diagnostics();if(busy.gpuInFlight!==2||busy.gpuBackPressureFrames<1)throw Error('Queue bound failed '+JSON.stringify(busy));await realFence();for(const release of held)release();await Promise.resolve();await Promise.resolve();device.queue.onSubmittedWorkDone=realFence;const recovered=app.diagnostics();if(recovered.gpuInFlight!==0)throw Error('Queue failed to recover');app.reset();app.renderer.onDeviceLost({message:'QA simulated device loss'});if(window.shoreBackend.backend!=='webgl2-fallback'||!window.shoreDiagnostics.firstError.includes('QA simulated device loss')||!element('legacy').srcdoc.includes('<html'))throw Error('Device loss was hidden');console.log(JSON.stringify({gpuQueueBound:2,skipped:busy.gpuBackPressureFrames,recovered:true,reset:true,deviceLossVisible:true,fallbackPrepared:true}));process.exit(0);
